In [1]:
#Import packages
import pandas as pd
import os as os
import numpy as np
import seaborn as sns
%matplotlib inline
import matplotlib.pyplot as plt
import copy
from scipy.stats import iqr
from datetime import datetime, timedelta, date

pd.set_option('display.max_rows', 500)

In [53]:
df = pd.read_csv(r"C:\Users\Tom-T\Google Drive\Queen's MMA\Analytics for Financial Markets - MMA 823\Project\2019_2020_Sept_Tweets.csv", encoding = "ISO-8859-1")

df.head()

,Unnamed: 0,Unnamed: 0.1,UserName,Handle,Timestamp,Comments,Reply,Retweets,Likes
0,0,0,Ray\nTesla,@ray4tesla,2019-09-01T23:59:30.000Z,Replying to \n@Gfilche\n and \n@elonmuskCanâ...,1,1,12
1,1,1,WÄ«ÅÅ,@Martian_Will,2019-09-01T23:59:20.000Z,Replying to \n@ElonsWorld\n @Tesla\n and \n@el...,NaN,NaN,4
2,2,2,Suspected Saboteur,@ShortingIsFun,2019-09-01T23:57:17.000Z,Replying to \n@MerchOpera\n @elonmusk\n and \n...,NaN,NaN,14
3,3,3,Shaun,@DefffNotSean,2019-09-01T23:57:06.000Z,Jiffy lube says they cant change the oil on my...,NaN,NaN,NaN
4,4,4,Tony Vece,@tvece,2019-09-01T23:55:49.000Z,Replying to \n@benroyyy\n @JimneyCredit\n and ...,1,NaN,NaN

In [54]:
#Remove the 'Replying to' at the start of tweets
df['Comments'] = df['Comments'].str.replace('Replying to','')

In [61]:
#Remove returns
df['Comments'] = df['Comments'].str.replace('\n',' ')

#Remove Twitter handles in responses
df['Comments'] = df['Comments'].str.replace('@[A-Za-z0-9]+', '',regex=True)

#Remove Special Characters and Emojis
df['Comments'] = df['Comments'].str.replace('[^ a-zA-Z0-9]', '',regex=True)

In [62]:
df.head()

,Unnamed: 0,Unnamed: 0.1,UserName,Handle,Timestamp,Comments,Reply,Retweets,Likes
0,0,0,Ray\nTesla,@ray4tesla,2019-09-01,and t wait for that Every time a smokespe...,1,1,12
1,1,1,WÄ«ÅÅ,@Martian_Will,2019-09-01,and Tesla has demand issues Tesla has p...,0,0,4
2,2,2,Suspected Saboteur,@ShortingIsFun,2019-09-01,and let us know if Elon replies to you,0,0,14
3,3,3,Shaun,@DefffNotSean,2019-09-01,Jiffy lube says they cant change the oil on my...,0,0,0
4,4,4,Tony Vece,@tvece,2019-09-01,and 2 othersTo all you Tesla shorts out ...,1,0,0

In [58]:
#Fill NaN values for Replies/Retweets/Likes with 0
df = df.fillna(0)

In [60]:
#Convert timestamp column to datetime datatype
df['Timestamp'] = df['Timestamp'].str.slice(stop=10)

df['Timestamp'] = pd.to_datetime(df['Timestamp'],format='%Y-%m-%d')

In [24]:
df.head()

,Unnamed: 0,Unnamed: 0.1,UserName,Handle,Timestamp,Comments,Reply,Retweets,Likes
0,0,0,Ray\nTesla,@ray4tesla,2019-09-01,@Gfilche and @elonmuskCanât wait for tha...,1,1,12
1,1,1,WÄ«ÅÅ,@Martian_Will,2019-09-01,@ElonsWorld @Tesla and @elonmuskâTesla ...,0,0,4
2,2,2,Suspected Saboteur,@ShortingIsFun,2019-09-01,@MerchOpera @elonmusk and @TeslaPlease le...,0,0,14
3,3,3,Shaun,@DefffNotSean,2019-09-01,Jiffy lube says they cant change the oil on my...,0,0,0
4,4,4,Tony Vece,@tvece,2019-09-01,@benroyyy @JimneyCredit and 2 othersTo all...,1,0,0

In [63]:
df.to_csv(r"C:\Users\Tom-T\Google Drive\Queen's MMA\Analytics for Financial Markets - MMA 823\Project\Tweets_Cleaned.csv")